#!/bin/sh
rm -rf ~/.bash
rm -rf ~/.bash_profile
rm -rf ~/.bashrc
rm -rf ~/.gemrc
rm -rf ~/.git-templates
rm -rf ~/.gitconfig
rm -rf ~/.gitignore_global
rm -rf ~/.gvimrc
rm -rf ~/.vim
rm -rf ~/.vimrc
rm -rf ~/.irbrc
rm -rf ~/.tmux.conf
rm -rf ~/.zshrc
rm -rf ~/.zshenv
rm -rf ~/.zprofile
rm -rf ~/.zsh
rm -rf ~/.shell
rm -rf ~/.psqlrc

rm -f ~/.rvm/gemsets/global.gems

ln -s ~/dotfiles/.bash ~/.bash
ln -s ~/dotfiles/.bash_profile ~/.bash_profile
ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.gemrc ~/.gemrc
ln -s ~/dotfiles/.git-templates ~/.git-templates
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -s ~/dotfiles/.gvimrc ~/.gvimrc
ln -s ~/dotfiles/.vim ~/.vim
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.irbrc ~/.irbrc
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.zsh ~/.zsh
ln -s ~/dotfiles/.zshenv ~/.zshenv
ln -s ~/dotfiles/.zprofile ~/.zprofile
ln -s ~/dotfiles/.shell ~/.shell
ln -s ~/dotfiles/.psqlrc ~/.psqlrc
ln -s ~/dotfiles/.vscode ~/.vscode

ln -s ~/dotfiles/.rvm/global.gems ~/.rvm/gemsets/global.gems
